"""
ev_analysis.py — Phase 9: Expected Value Framework

For every signal generated by signals.py, compute:
  - Win rate
  - Average win / average loss
  - Expected Value  = P(win) * avg_win - P(loss) * avg_loss
  - Edge ratio      = avg_win / |avg_loss|
  - t-statistic     = mean / (std / sqrt(n))
  - Annualized Sharpe

Slices
------
  1. By signal × lookahead            → ev_summary.csv
  2. By signal × ticker               → ev_by_ticker.csv
  3. By signal × HMM regime           → ev_by_regime.csv
  4. By signal × Bayesian regime      → ev_by_regime.csv  (same file, different rows)
  5. By factor score quartile         → ev_by_factor_quartile.csv

Visualization
-------------
  ev_analysis.png  — 2×3 grid summarising the above

Usage
-----
  python ev_analysis.py
"""

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats
from pathlib import Path

from config import FEATURE_DIR, VISUALIZATION_DIR, PROCESSED_DIR
from utils.tickers import load_tickers

# ── Output paths ──────────────────────────────────────────────────────────────

VISUALIZATION_DIR.mkdir(parents=True, exist_ok=True)
FEATURE_DIR.mkdir(parents=True, exist_ok=True)

LOOKAHEADS = [1, 5, 20]   # forward windows in trading days

FACTOR_SCORE_COLS = ["mom_score", "rev_score", "vol_score", "val_score", "qual_score"]


# ── Loaders ───────────────────────────────────────────────────────────────────

def load_signals() -> pd.DataFrame:
    path = FEATURE_DIR / "signals.csv"
    if not path.exists():
        raise FileNotFoundError(f"signals.csv not found in {FEATURE_DIR}. Run signals.py first.")
    df = pd.read_csv(path, index_col=0, parse_dates=True)
    df.index.name = "date"
    return df


def load_regime_cache(tickers: list[str]) -> pd.DataFrame:
    """
    Run detector.detect() once per ticker and stack into a long DataFrame.
    Columns kept: date, ticker, hmm_label, bayes_regime
    Cached to FEATURE_DIR/regime_cache.csv so repeated runs are fast.
    """
    cache_path = FEATURE_DIR / "regime_cache.csv"

    if cache_path.exists():
        print("  Loading regime cache from disk...")
        df = pd.read_csv(cache_path, index_col=0, parse_dates=True)
        df.index.name = "date"
        return df

    print("  Building regime cache (runs HMM + Bayesian for each ticker)...")

    # Import here to avoid circular issues if run standalone
    from detector import detect

    frames = []
    for ticker in tickers:
        print(f"    Detecting regimes — {ticker}")
        try:
            df = detect(ticker)
            df["ticker"] = ticker
            frames.append(df[["ticker", "hmm_label", "bayes_regime"]])
        except Exception as e:
            print(f"    Warning: could not detect regimes for {ticker}: {e}")

    if not frames:
        return pd.DataFrame(columns=["date", "ticker", "hmm_label", "bayes_regime"])

    combined = pd.concat(frames)
    combined.index.name = "date"
    combined.to_csv(cache_path)
    print(f"  Regime cache saved → {cache_path}")
    return combined


# ── Forward return construction ───────────────────────────────────────────────

def add_forward_returns(signals: pd.DataFrame) -> pd.DataFrame:
    """
    For each ticker, compute forward returns for each lookahead window
    and merge them back onto the signals DataFrame.

    Forward return for N days: the compounded return over the next N trading
    days, aligned to the signal date (i.e. signal on day t → return t+1..t+N).
    """
    signals = signals.copy()

    # Build a wide price/return matrix per ticker
    frames = []
    for ticker, grp in signals.groupby("ticker"):
        grp = grp.sort_index()
        for la in LOOKAHEADS:
            # Sum of log returns shifted back — equivalent to compounded return
            fwd = grp["daily_return"].rolling(la).sum().shift(-la)
            signals.loc[grp.index, f"fwd_{la}d"] = fwd

    return signals


# ── Core EV metrics ───────────────────────────────────────────────────────────

def ev_metrics(returns: pd.Series, label: str = "") -> dict:
    """Compute full EV metric set for a slice of forward returns."""
    r = returns.dropna()
    n = len(r)
    if n < 10:
        return None

    wins   = r[r > 0]
    losses = r[r <= 0]

    win_rate  = len(wins) / n
    loss_rate = 1 - win_rate
    avg_win   = wins.mean()   if len(wins)   > 0 else 0.0
    avg_loss  = losses.mean() if len(losses) > 0 else 0.0  # negative number

    ev = win_rate * avg_win + loss_rate * avg_loss   # avg_loss already negative

    edge_ratio = avg_win / abs(avg_loss) if avg_loss != 0 else np.nan

    mean_r = r.mean()
    std_r  = r.std()
    t_stat = (mean_r / (std_r / np.sqrt(n))) if std_r > 0 else np.nan
    p_val  = 2 * (1 - stats.t.cdf(abs(t_stat), df=n - 1)) if not np.isnan(t_stat) else np.nan

    # Annualize Sharpe assuming daily returns; scale by sqrt(252/la) handled by caller
    sharpe = (mean_r / std_r) * np.sqrt(252) if std_r > 0 else np.nan

    return {
        "label":      label,
        "n":          n,
        "win_rate":   round(win_rate,  4),
        "avg_win":    round(avg_win,   5),
        "avg_loss":   round(avg_loss,  5),
        "ev":         round(ev,        5),
        "edge_ratio": round(edge_ratio, 3) if not np.isnan(edge_ratio) else np.nan,
        "mean_ret":   round(mean_r,    5),
        "std_ret":    round(std_r,     5),
        "t_stat":     round(t_stat,    3) if not np.isnan(t_stat) else np.nan,
        "p_value":    round(p_val,     4) if not np.isnan(p_val)  else np.nan,
        "sharpe":     round(sharpe,    3) if not np.isnan(sharpe) else np.nan,
    }


# ── Slice 1: Signal × Lookahead ───────────────────────────────────────────────

def ev_by_signal_lookahead(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for signal in ["long", "short", "neutral"]:
        mask = df["signal"] == signal
        for la in LOOKAHEADS:
            col = f"fwd_{la}d"
            if col not in df.columns:
                continue
            m = ev_metrics(df.loc[mask, col], label=f"{signal}_{la}d")
            if m:
                m["signal"]    = signal
                m["lookahead"] = la
                rows.append(m)

    return pd.DataFrame(rows)


# ── Slice 2: Signal × Ticker ──────────────────────────────────────────────────

def ev_by_ticker(df: pd.DataFrame, lookahead: int = 5) -> pd.DataFrame:
    col = f"fwd_{lookahead}d"
    rows = []
    for (ticker, signal), grp in df.groupby(["ticker", "signal"]):
        m = ev_metrics(grp[col], label=f"{ticker}_{signal}")
        if m:
            m["ticker"]    = ticker
            m["signal"]    = signal
            m["lookahead"] = lookahead
            rows.append(m)
    return pd.DataFrame(rows)


# ── Slice 3 & 4: Signal × Regime ─────────────────────────────────────────────

def ev_by_regime(df: pd.DataFrame, regime_col: str, lookahead: int = 5) -> pd.DataFrame:
    if regime_col not in df.columns:
        return pd.DataFrame()

    col = f"fwd_{lookahead}d"
    rows = []
    for (signal, regime), grp in df.groupby(["signal", regime_col]):
        m = ev_metrics(grp[col], label=f"{signal}|{regime_col}={regime}")
        if m:
            m["signal"]     = signal
            m["regime_col"] = regime_col
            m["regime"]     = regime
            m["lookahead"]  = lookahead
            rows.append(m)
    return pd.DataFrame(rows)


# ── Slice 5: Factor Score Quartile ────────────────────────────────────────────

def ev_by_factor_quartile(df: pd.DataFrame, lookahead: int = 5) -> pd.DataFrame:
    col = f"fwd_{lookahead}d"
    rows = []
    available = [c for c in FACTOR_SCORE_COLS if c in df.columns]

    # Work on a reset-index copy so every row has a unique integer index.
    # This sidesteps all duplicate-date-index alignment issues.
    work = df.reset_index()  # 'date' becomes a regular column

    for factor in available:
        quartile_col = f"_q_{factor}"
        work[quartile_col] = pd.Series(pd.NA, index=work.index, dtype="object")

        for date, grp in work.groupby("date"):
            valid = grp[factor].dropna()
            if len(valid) < 4:
                continue
            try:
                labels = pd.qcut(
                    valid.rank(method="first"), 4,
                    labels=["Q1", "Q2", "Q3", "Q4"],
                    duplicates="drop",
                )
                work.loc[valid.index, quartile_col] = labels.astype(str).values
            except ValueError:
                continue

        for q in ["Q1", "Q2", "Q3", "Q4"]:
            mask = work[quartile_col] == q
            m = ev_metrics(work.loc[mask, col], label=f"{factor}_{q}")
            if m:
                m["factor"]    = factor
                m["quartile"]  = q
                m["lookahead"] = lookahead
                rows.append(m)

    return pd.DataFrame(rows)


# ── Visualization ─────────────────────────────────────────────────────────────

def plot_ev_analysis(
    summary:          pd.DataFrame,
    regime_hmm:       pd.DataFrame,
    regime_bayes:     pd.DataFrame,
    factor_quartiles: pd.DataFrame,
):
    fig = plt.figure(figsize=(18, 14))
    fig.suptitle("Phase 9 — Expected Value Framework", fontsize=15, fontweight="bold", y=0.98)
    gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.38)

    SIGNAL_COLORS = {"long": "#2ecc71", "short": "#e74c3c", "neutral": "#95a5a6"}

    # ── Panel 1: EV by signal × lookahead ─────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    for signal, color in SIGNAL_COLORS.items():
        sub = summary[summary["signal"] == signal].sort_values("lookahead")
        if sub.empty:
            continue
        ax1.plot(sub["lookahead"], sub["ev"], marker="o", label=signal, color=color, lw=2)
        ax1.fill_between(sub["lookahead"], 0, sub["ev"], alpha=0.08, color=color)
    ax1.axhline(0, color="black", lw=0.8, linestyle="--")
    ax1.set_title("Expected Value by Lookahead", fontweight="bold")
    ax1.set_xlabel("Lookahead (days)")
    ax1.set_ylabel("EV (avg daily return)")
    ax1.legend(fontsize=8)
    ax1.set_xticks(LOOKAHEADS)

    # ── Panel 2: Win rate by signal × lookahead ───────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    width = 0.25
    x = np.arange(len(LOOKAHEADS))
    for i, (signal, color) in enumerate(SIGNAL_COLORS.items()):
        sub = summary[summary["signal"] == signal].sort_values("lookahead")
        if sub.empty:
            continue
        ax2.bar(x + i * width, sub["win_rate"], width, label=signal, color=color, alpha=0.8)
    ax2.axhline(0.5, color="black", lw=0.8, linestyle="--", label="50%")
    ax2.set_title("Win Rate by Signal & Lookahead", fontweight="bold")
    ax2.set_xlabel("Lookahead (days)")
    ax2.set_ylabel("Win Rate")
    ax2.set_xticks(x + width)
    ax2.set_xticklabels([f"{la}d" for la in LOOKAHEADS])
    ax2.legend(fontsize=8)

    # ── Panel 3: Sharpe by signal × lookahead ─────────────────────────────────
    ax3 = fig.add_subplot(gs[0, 2])
    for signal, color in SIGNAL_COLORS.items():
        sub = summary[summary["signal"] == signal].sort_values("lookahead")
        if sub.empty:
            continue
        ax3.bar(
            [f"{la}d\n{signal}" for la in sub["lookahead"]],
            sub["sharpe"],
            color=color,
            alpha=0.85,
            label=signal,
        )
    ax3.axhline(0, color="black", lw=0.8, linestyle="--")
    ax3.set_title("Annualized Sharpe by Signal & Lookahead", fontweight="bold")
    ax3.set_ylabel("Sharpe Ratio")
    ax3.tick_params(axis="x", labelsize=7)
    ax3.legend(fontsize=8)

    # ── Panel 4: EV by HMM regime (long signals only, 5d lookahead) ───────────
    ax4 = fig.add_subplot(gs[1, 0])
    if not regime_hmm.empty:
        sub = regime_hmm[
            (regime_hmm["signal"] == "long") & (regime_hmm["lookahead"] == 5)
        ].sort_values("ev", ascending=False)
        colors = ["#2ecc71" if v >= 0 else "#e74c3c" for v in sub["ev"]]
        ax4.barh(sub["regime"], sub["ev"], color=colors, alpha=0.85)
        ax4.axvline(0, color="black", lw=0.8)
        ax4.set_title("Long Signal EV by HMM Regime (5d)", fontweight="bold")
        ax4.set_xlabel("Expected Value")
    else:
        ax4.text(0.5, 0.5, "No HMM regime data", ha="center", va="center",
                 transform=ax4.transAxes, color="gray")
        ax4.set_title("Long Signal EV by HMM Regime (5d)", fontweight="bold")

    # ── Panel 5: EV by Bayesian regime (long signals only, 5d lookahead) ──────
    ax5 = fig.add_subplot(gs[1, 1])
    if not regime_bayes.empty:
        sub = regime_bayes[
            (regime_bayes["signal"] == "long") & (regime_bayes["lookahead"] == 5)
        ].sort_values("ev", ascending=False)
        colors = ["#2ecc71" if v >= 0 else "#e74c3c" for v in sub["ev"]]
        ax5.barh(sub["regime"], sub["ev"], color=colors, alpha=0.85)
        ax5.axvline(0, color="black", lw=0.8)
        ax5.set_title("Long Signal EV by Bayesian Regime (5d)", fontweight="bold")
        ax5.set_xlabel("Expected Value")
    else:
        ax5.text(0.5, 0.5, "No Bayesian regime data", ha="center", va="center",
                 transform=ax5.transAxes, color="gray")
        ax5.set_title("Long Signal EV by Bayesian Regime (5d)", fontweight="bold")

    # ── Panel 6: Factor quartile EV (long - Q4 vs Q1, 5d) ────────────────────
    ax6 = fig.add_subplot(gs[1, 2])
    if not factor_quartiles.empty:
        sub = factor_quartiles[factor_quartiles["lookahead"] == 5]
        # Compute Q4 - Q1 spread per factor as a summary of monotonicity
        spreads = []
        for factor, grp in sub.groupby("factor"):
            q1 = grp[grp["quartile"] == "Q1"]["ev"].values
            q4 = grp[grp["quartile"] == "Q4"]["ev"].values
            if len(q1) > 0 and len(q4) > 0:
                spreads.append({
                    "factor":  factor.replace("_score", ""),
                    "spread":  round(float(q4[0] - q1[0]), 5),
                })
        if spreads:
            spread_df = pd.DataFrame(spreads).sort_values("spread", ascending=True)
            colors    = ["#2ecc71" if v >= 0 else "#e74c3c" for v in spread_df["spread"]]
            ax6.barh(spread_df["factor"], spread_df["spread"], color=colors, alpha=0.85)
            ax6.axvline(0, color="black", lw=0.8)
            ax6.set_title("Factor EV Spread: Q4 − Q1 (5d)", fontweight="bold")
            ax6.set_xlabel("EV Spread (Q4 − Q1)")
    else:
        ax6.text(0.5, 0.5, "No factor quartile data", ha="center", va="center",
                 transform=ax6.transAxes, color="gray")
        ax6.set_title("Factor EV Spread: Q4 − Q1 (5d)", fontweight="bold")

    out = VISUALIZATION_DIR / "ev_analysis.png"
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Visualization saved → {out}")


# ── Console summary ───────────────────────────────────────────────────────────

def print_summary(summary: pd.DataFrame):
    print(f"\n{'='*80}")
    print("  PHASE 9 — EXPECTED VALUE SUMMARY  (all tickers combined)")
    print(f"{'='*80}")
    print(f"  {'Signal':<8} {'LA':>4}  {'n':>6}  {'WinRate':>8}  {'AvgWin':>9}  "
          f"{'AvgLoss':>9}  {'EV':>9}  {'EdgeR':>7}  {'t-stat':>7}  {'p':>6}  {'Sharpe':>7}")
    print(f"  {'-'*78}")

    for _, row in summary.sort_values(["signal", "lookahead"]).iterrows():
        sig_str = {"long": "▲ long", "short": "▼ short", "neutral": "— neut"}.get(
            row["signal"], row["signal"]
        )
        p_str = f"{row['p_value']:.4f}" if not pd.isna(row.get("p_value")) else "  N/A "
        edge  = f"{row['edge_ratio']:.3f}" if not pd.isna(row.get("edge_ratio")) else "  N/A"
        t     = f"{row['t_stat']:+.3f}"   if not pd.isna(row.get("t_stat"))    else "  N/A"
        sh    = f"{row['sharpe']:+.3f}"   if not pd.isna(row.get("sharpe"))    else "  N/A"
        print(
            f"  {sig_str:<8} {int(row['lookahead']):>4}  {int(row['n']):>6}  "
            f"{row['win_rate']:>8.2%}  {row['avg_win']:>9.5f}  {row['avg_loss']:>9.5f}  "
            f"{row['ev']:>9.5f}  {edge:>7}  {t:>7}  {p_str:>6}  {sh:>7}"
        )

    print(f"\n  KEY: EV = P(win)*avg_win + P(loss)*avg_loss  |  EdgeR = avg_win/|avg_loss|")
    print(f"       t-stat > 2.0 (or < -2.0) suggests edge is statistically significant")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    tickers = load_tickers()

    print("Loading signals...")
    signals = load_signals()
    print(f"  {signals['ticker'].nunique()} tickers  |  "
          f"{signals.index.nunique()} dates  |  {len(signals):,} rows")

    print("\nAdding forward returns...")
    signals = add_forward_returns(signals)

    print("\nLoading regime labels...")
    regimes = load_regime_cache(tickers)

    # Join regime labels onto signals
    if not regimes.empty:
        regimes = regimes.reset_index()
        signals = signals.reset_index()
        signals = signals.merge(
            regimes[["date", "ticker", "hmm_label", "bayes_regime"]],
            on=["date", "ticker"],
            how="left",
        )
        signals = signals.set_index("date")
        print(f"  Regime coverage: {signals['hmm_label'].notna().mean():.1%} of rows")

    # ── Compute slices ─────────────────────────────────────────────────────────
    print("\nComputing EV slices...")

    summary          = ev_by_signal_lookahead(signals)
    ticker_ev        = ev_by_ticker(signals, lookahead=5)
    regime_hmm       = (ev_by_regime(signals, "hmm_label",    lookahead=5)
                        if "hmm_label"    in signals.columns else pd.DataFrame())
    regime_bayes     = (ev_by_regime(signals, "bayes_regime", lookahead=5)
                        if "bayes_regime" in signals.columns else pd.DataFrame())
    factor_quartiles = ev_by_factor_quartile(signals, lookahead=5)

    # Also compute regime slice for all lookaheads (saved to CSV)
    regime_hmm_full  = pd.DataFrame()
    regime_bayes_full = pd.DataFrame()
    if "hmm_label" in signals.columns:
        regime_hmm_full = pd.concat([
            ev_by_regime(signals, "hmm_label", la) for la in LOOKAHEADS
        ])
    if "bayes_regime" in signals.columns:
        regime_bayes_full = pd.concat([
            ev_by_regime(signals, "bayes_regime", la) for la in LOOKAHEADS
        ])
    regime_combined = pd.concat([regime_hmm_full, regime_bayes_full])

    # ── Save CSVs ──────────────────────────────────────────────────────────────
    print("\nSaving CSVs...")

    summary.to_csv(FEATURE_DIR / "ev_summary.csv", index=False)
    print(f"  Saved → {FEATURE_DIR / 'ev_summary.csv'}")

    ticker_ev.to_csv(FEATURE_DIR / "ev_by_ticker.csv", index=False)
    print(f"  Saved → {FEATURE_DIR / 'ev_by_ticker.csv'}")

    if not regime_combined.empty:
        regime_combined.to_csv(FEATURE_DIR / "ev_by_regime.csv", index=False)
        print(f"  Saved → {FEATURE_DIR / 'ev_by_regime.csv'}")

    factor_quartiles.to_csv(FEATURE_DIR / "ev_by_factor_quartile.csv", index=False)
    print(f"  Saved → {FEATURE_DIR / 'ev_by_factor_quartile.csv'}")

    # ── Print summary ──────────────────────────────────────────────────────────
    print_summary(summary)

    # ── Visualize ──────────────────────────────────────────────────────────────
    print("\nGenerating visualization...")
    plot_ev_analysis(summary, regime_hmm, regime_bayes, factor_quartiles)

    print("\nDone.")


if __name__ == "__main__":
    main()